### ISSUE TITLE
[Bug] Add start quests, please!

### ISSUE THREAD

**Issue by Takiusu** [Melledy/Grasscutter#1761] opened 2022-09-08 16:18 UTC
**Did you look for other closed issues that have the same problem?**
Yes

**Describe the bug**
Starting quests  after character creating are missing (for example, follow the Paimon).

**Which branch did you use?**
  Grasscutter version: 1.3.0-dev
  Git Hash: d80f313
-->

**Screenshots**

**Additional context**
Нет активных заданий - means "There is no active quests".

![image](https://user-images.githubusercontent.com/65616872/189173584-0d5414ce-f5ec-410f-ab21-cf040c1ee3b6.png)
![image](https://user-images.githubusercontent.com/65616872/189173606-0ec063cd-43d2-4028-b6a8-2a2ab56a50ff.png)
![image](https://user-images.githubusercontent.com/65616872/189173632-8e07fa8d-73d8-4c2e-ac3b-a567a07e1e2d.png)
![image](https://user-images.githubusercontent.com/65616872/189173665-2d2e2e5c-391b-45f1-a0a3-db5f6681c4db.png)

**Comment by Hartie95** [comment] 2022-09-08 16:20
You can add them with `/quest add 35104`.
There are still many problem with them though, so you will probably either be stuck at some point, or need to finsh part manually with `/quest finish [questId]`

**Comment by Takiusu** [comment] 2022-09-08 16:27
> You can add them with `/quest add 35104`. There are still many problem with them though, so you will probably either be stuck at some point, or need to finsh part manually with `/quest finish [questId]`

Thanks, but can you make them to appear after character's creation?

**Comment by Takiusu** [comment] 2022-09-08 16:30
> You can add them with `/quest add 35104`. There are still many problem with them though, so you will probably either be stuck at some point, or need to finsh part manually with `/quest finish [questId]`

Looks like there is a one more bug inside this quest, Paimon should fly to the Statue, but she is just standing at the same place.
![image](https://user-images.githubusercontent.com/65616872/189175647-af05a594-3f07-4cc3-976f-25f6068c426c.png)

**Comment by Hartie95** [comment] 2022-09-08 16:58
> > You can add them with `/quest add 35104`. There are still many problem with them though, so you will probably either be stuck at some point, or need to finsh part manually with `/quest finish [questId]`
> 
> Thanks, but can you make them to appear after character's creation?

Before thats done, we first need to fix the many problems with quests currently.

I'm currently looking into fixing some of them and getting the tutorial quests to run propperly. Some things like the quest progress with paimon at the beginning is fixed in my wip branch [here](https://github.com/hartie95/Grasscutter/tree/quests), you would need to compile it yourself though.

**Comment by Takiusu** [comment] 2022-09-08 17:10
> > > You can add them with `/quest add 35104`. There are still many problem with them though, so you will probably either be stuck at some point, or need to finsh part manually with `/quest finish [questId]`
> > 
> > 
> > Thanks, but can you make them to appear after character's creation?
> 
> Before thats done, we first need to fix the many problems with quests currently.
> 
> I'm currently looking into fixing some of them and getting the tutorial quests to run propperly. Some things like the quest progress with paimon at the beginning is fixed in my wip branch [here](https://github.com/hartie95/Grasscutter/tree/quests), you would need to compile it yourself though.

I see, it's very good! thank you for reply :)

**Comment by alt3ri** [comment] 2022-09-09 19:52
better not hoping private server should be the same as official server

**Comment by G-370** [comment] 2022-09-21 12:08
> 

alt3ri, that is not a productive remark

**Comment by KingRainbow44** [comment] 2023-04-08 07:24
duplicate of #165

**Closed as not planned by KingRainbow44** 2023-04-08 07:24 UTC
Labels: enhancement
