### ISSUE TITLE
[Bug] No element traveler doesn't have the correct skill depot

### ISSUE THREAD

**Issue by ERthereal** [Melledy/Grasscutter#2214] opened 2023-06-17 00:44 UTC
**Did you look for other closed issues that have the same problem?**

Yes.
**Describe the bug**

When a new account registers and enters the game, their traveler skill is activated normally, but the console reports an error [Called unknown condition handler NEW_ACTIVITY_COND_FINISH_MUSIC_GAME_ALL_LEVEL.] When they exit the game and re-enter, the console reports the same error. Afterwards, their traveler skill disappears.
**Which branch did you use?**

Grasscutter version: 1.6.1-dev
  Git Hash: 31cef88
**Screenshots**

**Additional context**

**Comment by KingRainbow44** [comment] 2023-06-17 01:58
this is currently semi-normal behavior (ie, it's been a long-standing issue that hasn't been fixed because of its minimal impact on gameplay), mainly the unknown condition handler

**Comment by Adelaide114514** [comment] 2023-06-17 03:05
> 这是目前半正常的行为（即，这是一个长期存在的问题，由于对游戏玩法的影响微乎其微，因此尚未解决），主要是未知条件处理程序
ok 在我来看，这并不是长期性问题，甚至是因为un和dev分支合并而使得gc更加向官服靠近导致的问题
因为增加了许多的判定，所以技能丢失你需要完成任务id为35205 鸟瞰风物 - 七天神像1解锁 在这之后旅行者技能就会恢复 下图即为例子:
ok in my opinion, this is not a long-term problem, even a problem caused by the merging of the un and dev branches, which brings gc closer to the official uniform
Due to the increased number of decisions, you need to complete the task id 35205 Bird 's-Eye View - Seven Days Idol 1 Unlock after this traveler's skills will be restored as an example:
![OA(G9$8MZR9RGA0 R`GZ7E5](https://github.com/Grasscutters/Grasscutter/assets/105539565/28ae0ade-a217-4810-be24-de3cddbf9f26)
![~VCPOJJBRD`@CZLB3UU)OZE](https://github.com/Grasscutters/Grasscutter/assets/105539565/9faa9b34-efd0-4df8-bd66-3041d06b9b04)
![GWUS2Y)`DQE( LZ96B2C2BJ](https://github.com/Grasscutters/Grasscutter/assets/105539565/0d84227e-aa0a-4845-b4bd-5a8e0b5ad3e3)
如果返回任务点你觉得很烦 你可以返回任务点 随后会触发剧情cg 然后你就可以正常游玩了 不会有任何bug
If you get bored going back to the quest point you can go back to the quest point and it will trigger the story cg and then you can play normally without any bugs

随后，在[https://github.com/Grasscutters/Grasscutter/issues/2213](url)中，你说drop.json迁移至res中并关停了此issue
我发现res中包含drop的早在3.2版本（或许更早）就出现了 我随后使用其他gc核心是有掉落产生的 随后我逐渐删除重启服务端以至于最后将所有的res内包含drop字符的都删除了还是有掉落，我将我更改过的drop.json放置data中 发现他居然生效了
所以说我的结论为 gc3.7最新版本中或许是引用出了问题而不是迁移至res中 而其它版本核心其实就是gc旧版本3.7的dev
（也就是最后更新时间为三周前的那个）
希望最新的分支能够赶紧修复 毕竟如果没有了掉落系统是一件很严重且难受的问题
Then, in the [https://github.com/Grasscutters/Grasscutter/issues/2213] (url), you said the drop json migrated to res and shut down in this issue
I found that res containing drop appeared as early as version 3.2 (maybe earlier), and then I used other gc cores, and there were drops. Then I gradually deleted and restarted the server so that finally all res containing drop characters were deleted or dropped. I put my changed drop.json in data and it actually worked
So my conclusion is that the latest version of gc3.7 is probably a reference problem rather than migrating to res and the other version core is actually the dev of the old version 3.7 of gc
(The one last updated three weeks ago)
Hopefully, the latest branch will be fixed quickly because it is a serious and painful problem without the drop system

**Comment by cyno-cyno** [comment] 2023-06-17 03:29
> > 这
Go to the support channel of discord to ask questions.

**Comment by KingRainbow44** [comment] 2023-08-30 01:19
fixed in #2314

**Closed as completed by KingRainbow44** 2023-08-30 01:19 UTC
Labels: bug
