### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by BergerLee** [Melledy/Grasscutter#545] opened 2022-05-05 12:09 UTC
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.def.AvatarData.getId()" because "data" is null
        at emu.grasscutter.game.avatar.Avatar.<init>(Avatar.java:122)
        at emu.grasscutter.game.avatar.Avatar.<init>(Avatar.java:117)
        at emu.grasscutter.server.packet.recv.HandlerSetPlayerBornDataReq.handle(HandlerSetPlayerBornDataReq.java:57)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:85)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:242)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by 4Benj** [comment] 2022-05-05 12:26
By any change have you edited any values within the database manually?

**Comment by liyongxinn** [comment] 2022-05-05 12:32
> 

no~

**Comment by BergerLee** [comment] 2022-05-05 12:33
> 通过任何更改，您是否手动编辑了数据库中的任何值？

no

**Comment by BergerLee** [comment] 2022-05-05 12:37
> By any change have you edited any values within the database manually?
This looks like a bug

**Comment by 4Benj** [comment] 2022-05-05 12:44
What were you doing before this error occurred?

**Comment by BergerLee** [comment] 2022-05-05 12:48
> What were you doing before this error occurred?
I am entering the game. If it is an existing user, this problem will cause the game to not report an error but cannot be displayed. The game page displays a white screen. If it is a newly created user, an error will be reported when choosing a name.

**Comment by 4Benj** [comment] 2022-05-05 13:10
I just tried my existing account and a new account in the dev branch and I have no issue. Are you also on the dev branch?

**Comment by BergerLee** [comment] 2022-05-05 13:17
> 我刚刚在 dev 分支中尝试了我现有的帐户和一个新帐户，我没有问题。你也在开发分支吗？

My Java version is 17 and mongodb version is 4.4, can I know your configuration?

**Comment by 4Benj** [comment] 2022-05-05 13:25
Build: Latest dev
OS: Windows 11 Pro x64
Java: openjdk 17.0.1 2021-10-19
Mongo: 5.0.6

**Comment by BS2800M** [comment] 2022-05-05 13:29
I have the same problem with null pointers
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.world.Scene.addPlayer(emu.grasscutter.game.player.Player)" because "scene" is null
        at emu.grasscutter.game.world.World.addPlayer(World.java:173)
        at emu.grasscutter.game.player.Player.onLogin(Player.java:1041)
        at emu.grasscutter.server.packet.recv.HandlerPlayerLoginReq.handle(HandlerPlayerLoginReq.java:45)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:85)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:242)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by 4Benj** [comment] 2022-05-05 13:34
I'm going to ask again, is this on the dev branch?

**Comment by BergerLee** [comment] 2022-05-05 13:39
> 我要再问一次，这是在开发分支上吗？

YES

**Comment by 4Benj** [comment] 2022-05-05 13:41
> I have the same problem with null pointers java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.world.Scene.addPlayer(emu.grasscutter.game.player.Player)" because "scene" is null

This is unrelated to the current issue

**Comment by BS2800M** [comment] 2022-05-05 13:46
> > I have the same problem with null pointers java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.world.Scene.addPlayer(emu.grasscutter.game.player.Player)" because "scene" is null
> 
> This is unrelated to the current issue

Although the error reporting prompt is different, I also report an error when entering an account that has been created, and an error when confirming the game name when creating a new account

**Comment by BS2800M** [comment] 2022-05-05 14:03
Well, I tried to delete the data in the database, and now the error is the same as him

**Comment by NekoparaAce** [comment] 2022-05-05 14:12
I also encountered the same situation as above.
The "Stable" branch works fine. However, when building the version of the "Dev" branch, after creating an account and entering the game, the network will be interrupted when entering a nickname, and then a white screen will be displayed.

I tried to delete the old database, but still can't enter the game.

My environment is as follows:
win11 pro 21H2
Java(TM) SE Development Kit 17.0.3.1(64-bit)
MongoDB 5.0.7 2008R2Plus SSL (64 bit)
MongDB Compass


` java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.world.Scene.addPlayer(emu.grasscutter.game.player.Player)" because "scene" is null
        at emu.grasscutter.game.world.World.addPlayer(World.java:173)
        at emu.grasscutter.game.player.Player.onLogin(Player.java:1041)
        at emu.grasscutter.server.packet.recv.HandlerPlayerLoginReq.handle(HandlerPlayerLoginReq.java:45)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:85)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:242)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by aldev814** [comment] 2022-05-05 14:20
This may be caused by the recent update in Dimbreath/GenshinData project, after using the 3.29 commit I don't have this problem

**Comment by NekoparaAce** [comment] 2022-05-05 14:48
> This may caused by the recent update in Dimbreath/GenshinData project, after using the 3.29 commit I don't have this problem

Yes, the problem is here, when I use Koko-boya's resources everything works fine

**Comment by MoonShadowIllusion** [comment] 2022-05-05 15:55
> > This may caused by the recent update in Dimbreath/GenshinData project, after using the 3.29 commit I don't have this problem
> 
> Yes, the problem is here, when I use Koko-boya's resources everything works fine

where can I download it

**Comment by MoonShadowIllusion** [comment] 2022-05-05 15:55
> > This may caused by the recent update in Dimbreath/GenshinData project, after using the 3.29 commit I don't have this problem
> 
> Yes, the problem is here, when I use Koko-boya's resources everything works fine

where can I download it

**Comment by NekoparaAce** [comment] 2022-05-05 16:12
> > > This may caused by the recent update in Dimbreath/GenshinData project, after using the 3.29 commit I don't have this problem
> > 
> > 
> > Yes, the problem is here, when I use Koko-boya's resources everything works fine
> 
> where can I download it

Because of the DMCA, I may not be able to share with you directly, you can search for this user's name on Github, you can find what you want.... Or you can get it from others via Discord

**Comment by BergerLee** [comment] 2022-05-06 03:00
> > > > This may caused by the recent update in Dimbreath/GenshinData project, after using the 3.29 commit I don't have this problem
> > > 
> > > 
> > > Yes, the problem is here, when I use Koko-boya's resources everything works fine
> > 
> > 
> > where can I download it
> 
> Because of the DMCA, I may not be able to share with you directly, you can search for this user's name on Github, you can find what you want.... Or you can get it from others via Discord

Thank you very much the problem has been solved

**Comment by cfuncode** [comment] 2022-05-06 14:48
> java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.def.AvatarData.getId()" because "data" is null at emu.grasscutter.game.avatar.Avatar.(Avatar.java:122) at emu.grasscutter.game.avatar.Avatar.(Avatar.java:117) at emu.grasscutter.server.packet.recv.HandlerSetPlayerBornDataReq.handle(HandlerSetPlayerBornDataReq.java:57) at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:85) at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:242) at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Thread.java:833)



> java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.def.AvatarData.getId()" because "data" is null at emu.grasscutter.game.avatar.Avatar.(Avatar.java:122) at emu.grasscutter.game.avatar.Avatar.(Avatar.java:117) at emu.grasscutter.server.packet.recv.HandlerSetPlayerBornDataReq.handle(HandlerSetPlayerBornDataReq.java:57) at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:85) at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:242) at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Thread.java:833)

你这个问题和我的这个问题好像
https://github.com/Grasscutters/Grasscutter/issues/555#issue-1227006275
已经解决了，是java bean属性和json文件的key不对应造成的

**Comment by lunaticwhat** [comment] 2022-05-08 09:34
Solved problem. Closed to cleanup the workspace.

**Closed as completed by lunaticwhat** 2022-05-08 09:34 UTC
Labels: bug
