### ISSUE TITLE
[Bug][Solved] Sinobu's skill is abnormal

### ISSUE THREAD

**Issue by einekuhmachtmuh** [Melledy/Grasscutter#2074] opened 2023-02-26 14:54 UTC
So far, I haven't seen similar issue, but have asked for support in Discord.

Main Problem:
At the moment of Shinobu's E casting, she heals the avatar twice, then no more healing.

 Grasscutter  Edition:
 version: 1.4.3-Release
  Git Hash: 5c4c62c

![BUG1](https://user-images.githubusercontent.com/26906084/221418113-5d37f7b6-dd4d-4b2d-baff-5842330d21f8.png)

Extra Info:
Damage of Shinobu's Q isn't in scale with her Life.

**Comment by NotThorny** [comment] 2023-02-27 05:28
Self-damage was never been implemented so it's not a bug that it isn't working. Healing abilities are also a bit patchwork in how they are implemented, they were not really 'implemented correctly'. Healing is defined manually per-character in HealAbilityManager, specifically Shinobu's abilities are defined here :
 https://github.com/Grasscutters/Grasscutter/blob/development/src/main/java/emu/grasscutter/game/ability/HealAbilityManager.java#L102
 
 You can then refer here to where ability modifiers are read from BinOutput in resources : 
 https://github.com/Grasscutters/Grasscutter/blob/development/src/main/java/emu/grasscutter/data/ResourceLoader.java#L292
 
 Then how that ability is handled by AbilityManager : 
 https://github.com/Grasscutters/Grasscutter/blob/development/src/main/java/emu/grasscutter/game/ability/AbilityManager.java#L153
 
 This isn't really a 'bug' as much as it is just not implemented. Healing being implemented 'correctly' would be the way to fix this and all other healing abilities.

**Comment by qingchunnh** [comment] 2023-05-04 17:47
#1199 參考

**Comment by einekuhmachtmuh** [comment] 2023-06-02 06:10
OK, I'll solve it on my own coding.

**Comment by NotThorny** [comment] 2023-06-02 07:29
Should be fixed in the most recent release of Grasscutter, actually. Abilities should be at least generally working correctly, including self-damage.

**Comment by einekuhmachtmuh** [comment] 2023-06-03 05:22
I have tested Shinobu, and her heal is properly fixed (in #2166). However, in 1.6.1 skill can't generate balls

https://github.com/Grasscutters/Grasscutter/assets/26906084/6024e5fd-8002-4896-875c-0577ab0f1fdc

This problem should be fixed after #2066.
The code of energy manger and generated proto seems to be the same as the previous "work" edition. I haven't checked the packets (packets plugin can't be loaded), so I'm not sure the cause.

**Comment by KingRainbow44** [comment] 2023-06-03 05:33
its the new ability system, which doesnt have elemental energy balls implemented

**Comment by einekuhmachtmuh** [comment] 2023-06-05 08:15
Generation of elemental balls has implemented in https://github.com/Grasscutters/Grasscutter/commit/b09c0d48bf1e812145f6c015104e5a69e6787935 commit.

**Closed as completed** 2023-06-05 08:33 UTC
Labels: bug
