### ISSUE TITLE
[Bug] 卡在命名界面确认戳不动(此时后台弹出了一个NPE(see ·Additional context))

### ISSUE THREAD

**Issue by Bread-NiceCat** [Melledy/Grasscutter#2071] opened 2023-02-24 14:22 UTC
**Did you look for other closed issues that have the same problem?**

no
**Describe the bug**

后台疯狂报GSON的错误+NPE+UID不对应+卡在命名界面无法确认
**Which branch did you use?**

游戏版本：3.4.0
Grasscutter 版本：1.4.6-b209d919
**Screenshots**

![image](https://user-images.githubusercontent.com/121159360/221201409-49e3bdb8-38ea-4eca-9fba-b188405c4e9c.png)
![image](https://user-images.githubusercontent.com/121159360/221201524-b0233d3e-e978-488b-9356-271180a0ba59.png)

****
**Additional context**

> java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.excels.QuestData.getId()" because "questData" is null
        at emu.grasscutter.game.quest.GameQuest.<init>(GameQuest.java:55)
        at emu.grasscutter.game.quest.GameMainQuest.addAllChildQuests(GameMainQuest.java:86)
        at emu.grasscutter.game.quest.GameMainQuest.<init>(GameMainQuest.java:78)
        at emu.grasscutter.game.quest.QuestManager.addMainQuest(QuestManager.java:178)
        at emu.grasscutter.game.quest.QuestManager.addQuest(QuestManager.java:197)
        at emu.grasscutter.game.player.PlayerProgressManager.addStatueQuestsOnLogin(PlayerProgressManager.java:186)
        at emu.grasscutter.game.player.PlayerProgressManager.onPlayerLogin(PlayerProgressManager.java:43)
        at emu.grasscutter.game.player.Player.onLogin(Player.java:1220)
        at emu.grasscutter.server.packet.recv.HandlerSetPlayerBornDataReq.handle(HandlerSetPlayerBornDataReq.java:68)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:93)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:222)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Bread-NiceCat** [comment] 2023-02-24 15:31
还有，我本来想用idea调试一下的，没想到连断点都没到就报错退出了.
貌似是mongodb的问题，但是我没用它过也不知道改怎么弄.
> Exception in thread "main" com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: no further information}}]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:177)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:127)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:87)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:258)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:182)
	at com.mongodb.client.internal.MongoCollectionImpl.executeCreateIndexes(MongoCollectionImpl.java:847)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:830)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:825)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:810)
	at dev.morphia.annotations.builders.IndexHelper.createIndex(IndexHelper.java:220)
	at dev.morphia.annotations.builders.IndexHelper.createIndex(IndexHelper.java:210)
	at dev.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:186)
	at emu.grasscutter.database.DatabaseManager.ensureIndexes(DatabaseManager.java:89)
	at emu.grasscutter.database.DatabaseManager.initialize(DatabaseManager.java:70)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:118)

> Task :run FAILED

Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-17.0.4.1\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by mcoi-dev** [comment] 2023-02-25 02:00
> 还有，我本来想用idea调试一下的，没想到连断点都没到就报错退出了. 貌似是mongodb的问题，但是我没用它过也不知道改怎么弄.
> 
> > Exception in thread "main" com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: no further information}}]
> > at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:177)
> > at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
> > at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:127)
> > at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:87)
> > at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:258)
> > at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:182)
> > at com.mongodb.client.internal.MongoCollectionImpl.executeCreateIndexes(MongoCollectionImpl.java:847)
> > at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:830)
> > at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:825)
> > at com.mongodb.client.internal.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:810)
> > at dev.morphia.annotations.builders.IndexHelper.createIndex(IndexHelper.java:220)
> > at dev.morphia.annotations.builders.IndexHelper.createIndex(IndexHelper.java:210)
> > at dev.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:186)
> > at emu.grasscutter.database.DatabaseManager.ensureIndexes(DatabaseManager.java:89)
> > at emu.grasscutter.database.DatabaseManager.initialize(DatabaseManager.java:70)
> > at emu.grasscutter.Grasscutter.main(Grasscutter.java:118)
> 
> > Task :run FAILED
> 
> Execution failed for task ':run'.
> 
> > Process 'command 'C:\Program Files\Java\jdk-17.0.4.1\bin\java.exe'' finished with non-zero exit value 1
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.

我也遇到过，直接重新安装Mongodb就完了,win看一下服务端开没开

不过话说回来mongodb连接不上不应该是服务端刚启动然后加载完res和textmap后就3000毫秒超时报错的吗？

**Comment by NotThorny** [comment] 2023-02-25 06:29
Duplicate of #2062 and #2059

**Closed as not planned** 2023-04-14 07:01 UTC
Labels: bug
