### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by w3bOs** [Melledy/Grasscutter#1725] opened 2022-08-29 06:37 UTC
**Did you look for other closed issues that have the same problem?**

Yes
**Describe the bug**

Appears to be a scene error i think

**Which branch did you use?**

**Screenshots**
08:27:51 <ERROR:SceneScriptManager> [LUA] call trigger failed condition_EVENT_ENTER_REGION_289,emu.grasscutter.scripts.data.ScriptArgs@5856b839
org.luaj.vm2.LuaError: script:2394 bad argument: userdata expected, got number
        at org.luaj.vm2.LuaValue.argerror(Unknown Source)
        at org.luaj.vm2.LuaValue.checkuserdata(Unknown Source)
        at org.luaj.vm2.lib.jse.JavaMethod.call(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.call(Unknown Source)
        at emu.grasscutter.scripts.SceneScriptManager.safetyCall(SceneScriptManager.java:375)
        at emu.grasscutter.scripts.SceneScriptManager.callScriptFunc(SceneScriptManager.java:368)
        at emu.grasscutter.scripts.SceneScriptManager.realCallEvent(SceneScriptManager.java:323)
        at emu.grasscutter.scripts.SceneScriptManager.lambda$callEvent$10(SceneScriptManager.java:308)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Additional context**

Is a weird bug. If it appears, some chests dissapear or something.

**Comment by akatatsu27** [comment] 2022-08-29 11:21
duplicate of #1703

**Comment by Hartie95** [comment] 2022-09-07 20:27
As I mentioned here: https://github.com/Grasscutters/Grasscutter/issues/1703#issuecomment-1239836750

> latest resources should fix this problem, some others problems are still left, like some missing methods, some hidden quests that are not activated, some missing quest triggers, and some bugs in the scriptLib itself.
> I'm currently looking into it, and for now got quests working until the point where you need to kill the slime the second time after getting the element.

**Comment by Maik2007** [comment] 2022-09-09 11:55
i want to know what i have to do if cultivation tells me that he couldn't patch the game?

**Closed as completed** 2022-10-29 13:23 UTC
Labels: bug
