### ISSUE TITLE
Unterminated object at line 22442 column 76 path $

### ISSUE THREAD

**Issue by mofayukeji** [Melledy/Grasscutter#184] opened 2022-04-24 09:29 UTC
when i use:"java -jar grasscutter.jar -handbook"  the cmd allways said:

Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 22442 column 76 path $.
        at com.google.gson.Gson.fromJson(Gson.java:947)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at emu.grasscutter.tools.Tools.createGmHandbook(Tools.java:34)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:62)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 22442 column 76 path $.
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:490)
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        ... 3 more

i don`t know why.
and if i ignore this ,just run:"java -jar grasscutter.jar" that`s ok ,the server can run successfully.

bug when i join the game ,the registration interface is blank (the cmd can show :some one try login,and the database is empty)
maybe there's something wrong,can someone help me?thanks~

**Comment by memetrollsXD** [comment] 2022-04-24 09:53
Your JSON looks a bit malformed, how did you install binoutput/excelbinoutput?

**Comment by luckykeeper** [comment] 2022-04-24 11:19
seem same with #17

**Comment by memetrollsXD** [comment] 2022-04-24 11:20
Duplicate of #17

**Closed as completed by memetrollsXD** 2022-04-24 11:20 UTC

**Comment by mofayukeji** [comment] 2022-04-24 13:56
> Duplicate of #17

thanks！

**Comment by mofayukeji** [comment] 2022-04-24 13:56
> seem same with #17

thanks！
