### ISSUE TITLE
[Bug] 4206 error if both grasscutter and mitmproxy enabled SSL encryption on v1.6.1

### ISSUE THREAD

**Issue by Paper-Folding** [Melledy/Grasscutter#2185] opened 2023-06-03 10:01 UTC
**Did you look for other closed issues that have the same problem?**

Yes.

**Describe the bug**

Starting for v1.6.0 release, encryption causing 4206 error on client,  
i.e. set `"useEncryption": true, "useInRouting": true` for `config.json` and `USE_SSL = True` for `proxy_config.py`, set up proxy and other steps correctly, start the client, 4206 is shown.  
From mitmproxy console, I can see a 400 bad request of `/query_cur_region` api.  
On previous version (e.g. c4f1208f45c3c649114adb5b8bf185cfbafe785b for REL3.6), this issue does not exists.  
Disable the SSL encryption resolves the problem which is the default behavior of Cultivation.  

**Which branch did you use?**

[development](https://github.com/Grasscutters/Grasscutter/tree/development) branch, release [v1.6.1](https://github.com/Grasscutters/Grasscutter/releases/tag/v1.6.1)

**Screenshots**

**Additional context**

**Comment by KingRainbow44** [comment] 2023-06-03 14:50
semi-duplicate of #2184, see comment i put there for details. chances are you aren’t connecting via ‘127.0.0.1’, the IP address on the `keystore.p12` file.

**Closed as not planned by KingRainbow44** 2023-06-03 14:50 UTC
Labels: bug
