### ISSUE TITLE
/talent command doesn't work properly

### ISSUE THREAD

**Issue by SunshineVX** [Melledy/Grasscutter#587] opened 2022-05-06 13:49 UTC
After a talent level is changed,it will be reseted to 1 somehow.

**Comment by SunshineVX** [comment] 2022-05-06 14:16
This appears when a character joins or quits the team.

**Comment by lunaticwhat** [comment] 2022-05-06 15:01
have you try to re-login into the game after changing talent levels ?
everything related to user database modification should be need a re-login.

**Comment by SunshineVX** [comment] 2022-05-06 15:23
> have you try to re-login into the game after changing talent levels ? everything related to user database modification should be need a re-login.

But it worked well in previous versions.I just notice this problem today after i update it to latest dev.

**Comment by lunaticwhat** [comment] 2022-05-06 15:59
thanks for those bug reports. marked as to-do.

**Comment by DaisenSun** [comment] 2022-05-06 16:00
I have encountered the same problem. After testing, in the current version, there is no change after the talent upgrade and before the upgrade. I don't know what the problem is

**Comment by Danii57** [comment] 2022-05-06 21:49
yeah its happening to me too.

**Closed as completed** 2022-05-09 13:40 UTC
Labels: help wanted, todo
