### ISSUE TITLE
可以封装成Docker镜像吗？

### ISSUE THREAD

**Issue by 2168028160** [Melledy/Grasscutter#1334] opened 2022-06-21 09:01 UTC
把编译安装好的程序打包成Docker镜像即可，方便用户安装，也方便版本更新。

**Comment by KingRainbow44** [comment] 2022-06-21 19:04
duplicate of #686
yes grasscutter can be contained in a docker image, it just hasn't been done for reasons stated in the mentioned issue

**Closed as completed by KingRainbow44** 2022-06-21 19:04 UTC
Labels: enhancement, suggestion
