### ISSUE TITLE
[Bug] Blessing system damaged

### ISSUE THREAD

**Issue by ZXAS007** [Melledy/Grasscutter#1326] opened 2022-06-20 07:57 UTC
The currency required for the lottery becomes Mora, the button interface cannot be clicked, and the suspended animation is stuck.![IMG_20220620_155723.jpg](https://user-images.githubusercontent.com/69531154/174553169-8cdcb79e-dbc7-4395-ae93-96247893ee27.jpg)

1.2.1-dev-24bf5af

**Comment by KiminaNatsuki** [comment] 2022-06-20 14:44
(Perhaps you should just use chinese instead of the machine translation next time.)

**Comment by dianwangwin** [comment] 2022-06-20 15:21
> The currency required for the lottery becomes Mora, the button interface cannot be clicked, and the suspended animation is stuck.![IMG_20220620_155723.jpg](https://user-images.githubusercontent.com/69531154/174553169-8cdcb79e-dbc7-4395-ae93-96247893ee27.jpg)
> 
> 1.2.1-dev-24bf5af

check for resource

**Comment by KiminaNatsuki** [comment] 2022-06-20 15:24
Nah, it's a duplicate of #1325

**Closed as completed** 2022-06-20 16:40 UTC
Labels: bug
