### ISSUE TITLE
The effect of command "stats" disappear after only one attack.

### ISSUE THREAD

**Issue by Lynricsy** [Melledy/Grasscutter#356] opened 2022-04-29 11:02 UTC
After I use the command "stats",the attribute of the character changed for a while,but it returned to normal after I made an attack.

**Comment by memetrollsXD** [comment] 2022-04-29 11:08
Duplicate of #91

**Closed as completed by memetrollsXD** 2022-04-29 11:08 UTC

**Comment by alt3ri** [comment] 2022-04-29 11:12
it's normal for me?
