### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by simple-shadow** [Melledy/Grasscutter#1153] opened 2022-06-02 10:31 UTC
**Is your feature request related to a problem? Please describe.**

1. Bennett Elemental Outbreak (Zhongli 6c xinqiu and so on) does not heal 2. Teapot does not work properly, can not place and move furniture, and there is no interface for making furniture, 3. Other small props except teapot cannot be used, Internal server error 
**Describe the solution you'd like**

fix it!
**Describe alternatives you've considered**

command heal but it is trouble
**Additional context**

thank you!

**Comment by 4Benj** [comment] 2022-06-02 10:50
Duplicate of many other issues. Please use the search function before submitting an issue.

**Closed as completed by 4Benj** 2022-06-02 10:50 UTC
Labels: enhancement, suggestion
