### ISSUE TITLE
[Bug] Yelan Talents-Turn Coutrol has no effect

### ISSUE THREAD

**Issue by qingchunnh** [Melledy/Grasscutter#1130] opened 2022-05-31 18:54 UTC
Yelan Talents-Turn Coutrol has no effect
夜兰天赋-猜先有方没有效果
Also, Yelan will not reply Stamina when casting Elemental Skill
还有夜兰在施放元素战技不会像官方服务器一样回复体力

**Comment by AZthemute** [comment] 2022-05-31 19:17
Lots of talents have no effects yet.

**Comment by memetrollsXD** [comment] 2022-06-01 09:52
This isn't a bug, and a lot of features regarding character skills aren't implemented. Duplicate of a lot of issues

**Closed as not planned** 2022-06-01 09:52 UTC
Labels: bug
